#!/usr/bin/env bash

# scriptDir="$(realpath --canonicalize-missing "${BASH_SOURCE[0]}/..")"
storageDir="$HOME/.local/share/qemu-launcher"

#@formatter:off

[[ -z $QEMU_LAUNCHER_MENU ]] && {
    # shellcheck disable=SC2015
    [[ -n $WAYLAND_DISPLAY ]] && {
        command -v fuzzel >/dev/null 2>&1 && {
            QEMU_LAUNCHER_MENU="fuzzel --dmenu"
        } || {
        command -v tofi >/dev/null 2>&1 && {
            QEMU_LAUNCHER_MENU="tofi"
        } || {
        command -v rofi >/dev/null 2>&1 && {
            QEMU_LAUNCHER_MENU="rofi"
        } || {
        command -v wofi >/dev/null 2>&1 && {
            QEMU_LAUNCHER_MENU="wofi"
        }; }; }; }
    } || {
        command -v fzf >/dev/null 2>&1 && {
            QEMU_LAUNCHER_MENU="fzf"
        }
    } || {
        echo "Proper Menu not found! fuzzel|tofi|rofi|wofi|fzf"
        exit 1
    }
}

pickMenu(){ # {{{
    eval "$QEMU_LAUNCHER_MENU $*"
} # }}}

checkLatestFile(){
    local dirName; dirName="$1"
    [[ "${dirName:(-1)}" != "/" ]] && dirName+="/"
    find "$dirName" -follow -type f -printf "%T@ %p\n" | sort | tail -n1 | cut -d ' ' '-f2-'
}

maxRam="$(( $(grep --extended-regexp "MemTotal" /proc/meminfo | sed --expression='s/[^0-9]//g') / (1024 * 1024) ))" # {{{
logialCores="$(grep -i --extended-regexp -c '^processor' /proc/cpuinfo)"
# shellcheck disable=SC2034
[[ -z "$QEMU_RAM_SIZE" ]] && QEMU_RAM_SIZE="$(( maxRam / 2 ))G"
# shellcheck disable=SC2034
[[ -z "$QEMU_CPU_CORES" ]] && QEMU_CPU_CORES="$(( logialCores / 2 ))" # }}}

changeQemuRam(){ # {{{
    echo "$(
        echo -en "$(
            for (( i = 1; i <= maxRam; i++)) do
                printf "%s Gibibytes of RAM\n" "$i"
            done
        )"\
        |
        pickMenu "$*"\
        |
        grep -oE '^[0-9]+'
    )G"
} # }}}

changeQemuCpu(){ # {{{
    echo -en "$(
        for (( i = 1; i <= logialCores; i++)) do
            printf "%s core\n" "$i"
        done
    )"\
    |
    pickMenu "$*"\
    |
    grep -oE '^[0-9]+'
} # }}}

launchQemu(){ #{{{
    qemuHostPort="10022"
    executeCommand="qemu-system-x86_64\
        -enable-kvm\
        -m \"\$QEMU_RAM_SIZE\"\
        -cpu host\
        -smp \"\$QEMU_CPU_CORES\"\
        -net nic\
        -net user,hostfwd=tcp::$qemuHostPort-:22\
        -drive file=\"\$1\""

    [[ -n $2 ]] && executeCommand="${executeCommand} -cdrom \"\$2\" -boot order=d"

    if [[ -z $3 || $3 == "gui" ]]; then
        eval "${executeCommand} -vga virtio -display gtk,gl=on"
    # elif [[ $3 == "ssh" ]]; then
    #     sshCommand="ssh -t $USER@localhost -p$qemuHostPort 'tmux' || ( ssh-keygen -R '[localhost]:$qemuHostPort' && ssh -t $USER@localhost -p$qemuHostPort 'tmux' )"
    #     if pgrep -f "qemu.+$1"; then
    #         tmuxPaneOrTerminal "kitty" "$sshCommand"
    #     else
    #         eval "${executeCommand} -vga none -display none" & tmuxPaneOrTerminal "kitty" "$sshCommand"
    #     fi
    elif [[ $3 == "qemu-TUI" ]]; then
        local mountDir
        [[ -n "$2" ]] && {
            mountDir="$storageDir/mounts/$(echo "$2" | grep -oE '[^/]+$')"
        } || {
            mountDir="$storageDir/mounts/$(echo "$1" | grep -oE '[^/]+$')"
        }
        [[ $QEMU_DEBUG == true ]] && echo "|QEMU_DEBUG|\$mountDir|'$mountDir'"
        local password
        # shellcheck disable=SC2015
        local openNBD
        [[ -n "$2" ]] && {
            [[ $QEMU_LAUNCHER_MENU != "fzf" ]] && {
                password="$(pickMenu --prompt="Password: ")"
                echo "$password" | sudo -S mount --read-only --onlyonce --mkdir "$2" "$mountDir"
            } || {
                sudo mount --read-only --onlyonce --mkdir "$2" "$mountDir"
            }
            # shellcheck disable=SC2015
            echo "$2" | grep -E "arch" && {
                executeCommand+=" -kernel $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^linux\s*(.)/\1/p"\
                        "$mountDir/loader/entries/01-archiso-x86_64-linux.conf")\
                -initrd $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^initrd\s*(.)/\1/p"\
                        "$mountDir/loader/entries/01-archiso-x86_64-linux.conf")\
                -append '$(
                    sed\
                        --quiet\
                        -E "s/^options\s*(.)/\1/p"\
                        "$mountDir/loader/entries/01-archiso-x86_64-linux.conf"
                    ) console=ttyS0' -nographic"
            } || { echo "$2" | grep -E "gentoo" && {
                executeCommand+=" -kernel $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^\s*linux\s*(\S+).+/\1/p"\
                        "$mountDir/boot/grub/grub.cfg" | head -n1)\
                -initrd $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^\s*initrd\s*(.+)/\1/p"\
                        "$mountDir/boot/grub/grub.cfg" | head -n1)\
                -append '$(
                    sed\
                        --quiet\
                        -E "s/^\s*linux\s*\S+\s*(.+)/\1/p"\
                        "$mountDir/boot/grub/grub.cfg" | head -n1
                    ) console=ttyS0' -nographic"
            } || { echo "$2" | grep -E "nix" && {
                executeCommand+=" -kernel $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^LINUX\s*(.+)/\1/p"\
                        "$mountDir/isolinux/isolinux.cfg" | head -n1)\
                -initrd $mountDir$(
                    sed\
                        --quiet\
                        -E "s/^\s*INITRD\s*(.+)/\1/p"\
                        "$mountDir/isolinux/isolinux.cfg" | head -n1)\
                -append '$(
                    sed\
                        --quiet\
                        -E "s/^\s*APPEND\s*\S+\s*(.+)/\1/p"\
                        "$mountDir/isolinux/isolinux.cfg" | head -n1
                    ) console=ttyS0' -nographic"
            };};}
        } || {
            [[ -d "$storageDir/kernels" ]] || mkdir --parents "$storageDir/kernels"
            [[ -d "$storageDir/initrds" ]] || mkdir --parents "$storageDir/initrds"
            echo "$1" | grep -E 'gentoo' && {
                lsmod | grep -q 'nbd' || sudo modprobe nbd
                openNBD="$(lsblk -no PATH,MOUNTPOINT /dev/nbd* | sed -E '/^(\S+)\s+(\S+)/d' | head -n1 | grep -oE '^\S+')"
                [[ $QEMU_DEBUG == true ]] && echo "|QEMU_DEBUG|\$openNBD|'$openNBD'"
                sudo qemu-nbd --read-only --connect="$openNBD" "$1"
                local partitions
                partitions="$( lsblk -no PATH,TYPE "$openNBD" | sed -nE 's/^(\S+)\s+part/\1/p')"
                local numberOfParitions
                numberOfParitions="$(printf "%s\n" "$partitions" | wc -l)"
                [[ "$numberOfParitions" -gt 1 ]] && {
                    partition="$(printf "%s\n" "$partitions" | pickMenu )"
                } || {
                    [[ $numberOfParitions == 1 ]] && {
                        partition="$partitions"
                    } || {
                        echo "no partition found"
                        exit 1
                    }
                }
                [[ $QEMU_DEBUG == true ]] && echo "|QEMU_DEBUG|\$partition|'$partition'"
                [[ $QEMU_LAUNCHER_MENU != "fzf" ]] && {
                    password="$(pickMenu --prompt="Password: ")"
                    echo "$password" | sudo -S mount --read-only --onlyonce --mkdir "$partition" "$mountDir"
                } || {
                    sudo mount --read-only --onlyonce --mkdir "$partition" "$mountDir"
                }
                local imgKernelpath
                imgKernelpath="$mountDir$(
                    sudo sed\
                        -nE 's/^\s*linux\s*(\S+).+/\1/p'\
                        "$mountDir/boot/grub/grub.cfg" | head -n1
                    )"
                local imgInitRDpath
                imgInitRDpath="$mountDir$(
                    sudo sed\
                        -nE 's/^\s*initrd\s*(.+)/\1/p'\
                        "$mountDir/boot/grub/grub.cfg" | head -n1
                    )"
                local kernelArgs
                kernelArgs="'$(
                    sudo sed\
                        -nE 's/^\s*linux\s*\S+\s+(.+)/\1/p'\
                        "$mountDir/boot/grub/grub.cfg" | head -n1
                    ) console=ttyS0'"
                diff -q "$storageDir/kernels/$1-default-kernel" "$imgKernelpath" || {
                    cp "$imgKernelpath" "$storageDir/kernels/gentoo-latest-default-kernel"
                }
                diff -q "$storageDir/kernels/$1-default-initrd" "$imgInitRDpath" || {
                    cp "$imgInitRDpath" "$storageDir/initrds/gentoo-latest-default-initrd"
                }
                [[ "$QEMU_LAUNCHER_MENU" != "fzf" ]] && {
                    sudo -S umount "$mountDir"
                } || {
                    sudo umount "$mountDir"
                }
                executeCommand+=" -kernel $storageDir/kernels/$1-default-kernel\
                    -initrd $storageDir/initrds/$1-default-initrd\
                    -append $kernelArgs -nographic"
            }
        } || {
            echo "This distro currently isn't supported for manual booting."
            echo "Which is needed for appending some kernel args so everything works properly"
            exit 0
        }
        eval "echo \"$executeCommand\""
        [[ $QEMU_DEBUG == true ]] && eval "echo -en \"$executeCommand\""
        # shellcheck disable=SC2015
        [[ "$QEMU_LAUNCHER_MENU" != "fzf" ]] && {
            sudo -S umount "$mountDir"
        } || {
            sudo umount "$mountDir"
        }
        [[ -z "$2" ]] || {
            [[ $QEMU_DEBUG == true ]] && echo "|QEMU_DEBUG|\$openNBD|'$openNBD'"
            sudo qemu-nbd --disconnect "$openNBD"
        }
    fi
} #}}}

declare -A settings=( # {{{
    [" Memory"]="QEMU_RAM_SIZE=\"\$(changeQemuRam)\""
    [" Cpu"]="QEMU_CPU_CORES=\"\$(changeQemuCpu)\""
) # }}}

# shellcheck disable=SC2120
changeQemuSettings(){ # {{{
    chosen="$(echo -en "$(
        for item in "${!settings[@]}"; do
            printf "%s \n" "$item"
        done
    )"\
    |
        pickMenu "$*"\
    |
        sed 's/.$//'
    )"

    [[ -n $chosen ]] && eval "${settings["$chosen"]}"

} # }}}

createQemuImage(){ # {{{
    if [[ ! -f "$1" ]]; then
        echo "latest drive not found"
        qemu-img create -f qcow2 "$1" "$(
            echo -en "$(
                for (( i = 1; i<= 30; i++))  do
                    printf "%s G\n" "$i"
                done
            )"\
            |
            pickMenu\
            |
            grep -oE '^[0-9]+'
        )G"
    fi

} # }}}

installAlpineIso(){ # {{{
    if [[ ! -f "$storageDir/isos/alpine-virt-latest.iso" ]] ; then
        echo "alpine not found"
        wget\
            --no-use-server-timestamps\
            --directory-prefix="$storageDir/isos"\
            "$(
                curl https://alpinelinux.org/downloads/\
                |
                grep -E 'alpine-virt\S+-x86_64.iso"'\
                |
                sed -E 's/.+href="//; s/".+//; s/\&#x2F;/\//g'
            )"

        fileName="$(checkLatestFile "$storageDir/isos")"
        mv "$fileName" "$storageDir/isos/alpine-virt-latest.iso"
    fi
} # }}}

# shellcheck disable=SC2120
launchAlpineInstaller(){ # {{{
    installAlpineIso
    createQemuImage "$storageDir/images/alpine-virt-latest-drive.img"
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/alpine-virt-latest-drive.img" "$storageDir/isos/alpine-virt-latest.iso"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/alpine-virt-latest-drive.img" "$storageDir/isos/alpine-virt-latest.iso" "qemu-TUI"
    };}
} # }}}

launchAlpine(){ # {{{
    [[ ! -f "$storageDir/images/alpine-virt-latest-drive.img" ]] && {
        launchAlpineInstaller
        exit 0;
    }
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/alpine-virt-latest-drive.img"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/alpine-virt-latest-drive.img" "" "qemu-TUI"
    };}
} # }}}

installGentooIso(){ # {{{
    [[ ! -f "$storageDir/isos/gentoo-latest.iso" ]] && {
        echo "gentoo not found"
        wget\
            --no-use-server-timestamps\
            --directory-prefix="$storageDir/isos"\
            "$(
                curl https://www.gentoo.org/downloads/\
                |
                grep -oE 'https://\S+install-amd64-minimal\S+.iso'\
                |
                head -n1
            )"

        fileName="$(checkLatestFile "$storageDir/isos")"
        mv "$fileName" "$storageDir/isos/gentoo-latest.iso"
    }
} # }}}

# shellcheck disable=SC2120
launchGentooInstaller(){ # {{{
    installGentooIso
    createQemuImage "$storageDir/images/gentoo-latest-drive.img"
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/gentoo-latest-drive.img" "$storageDir/isos/gentoo-latest.iso"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/gentoo-latest-drive.img" "$storageDir/isos/gentoo-latest.iso" "qemu-TUI"
    };}
} # }}}

launchGentoo(){ # {{{
    [[ ! -f "$storageDir/images/gentoo-latest-drive.img" ]] && {
        launchGentooInstaller
        exit 0;
    }
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/gentoo-latest-drive.img"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/gentoo-latest-drive.img" "" "qemu-TUI"
    };}
} # }}}

installNixIso(){ # {{{
    [[ ! -f "$storageDir/isos/nix-latest.iso" ]] && {
        echo "nix not found"
        wget\
            --no-use-server-timestamps\
            --directory-prefix="$storageDir/isos"\
            "$(
                curl https://nixos.org/download/\
                |
                grep -oE 'https://\S+latest-nixos-minimal-x86_64-linux\.iso'\
                |
                head -n1
            )"

        fileName="$(checkLatestFile "$storageDir/isos")"
        mv "$fileName" "$storageDir/isos/nix-latest.iso"
    }
} # }}}

# shellcheck disable=SC2120
launchNixInstaller(){ # {{{
    installNixIso
    createQemuImage "$storageDir/images/nix-latest-drive.img"
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/nix-latest-drive.img" "$storageDir/isos/nix-latest.iso"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/nix-latest-drive.img" "$storageDir/isos/nix-latest.iso" "qemu-TUI"
    };}
} # }}}

launchNix(){ # {{{
    [[ ! -f "$storageDir/images/nix-latest-drive.img" ]] && {
        launchNixInstaller
        exit 0;
    }
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/nix-latest-drive.img"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/nix-latest-drive.img" "" "qemu-TUI"
    };}
} # }}}

installArchIso(){ # {{{
    # https://geo.mirror.pkgbuild.com/iso/2025.05.01/archlinux-2025.05.01-x86_64.iso
    [[ ! -f "$storageDir/isos/arch-latest.iso" ]] && {
        echo "arch not found"
        downloadLink="$(curl https://archlinux.org/download/ | grep -oE 'https://geo\.mirror\.pkgbuild\.com/iso/\S+/')"
        wget\
            --no-use-server-timestamps\
            --directory-prefix="$storageDir/isos"\
            "${downloadLink}$(
                curl "$downloadLink"\
                    |
                grep -oE 'archlinux-[0-9]+.+x86_64.iso'\
                |
                head -n1\
                |
                sed -E 's/".+//'
            )"

        fileName="$(checkLatestFile "$storageDir/isos")"
        mv "$fileName" "$storageDir/isos/arch-latest.iso"
    }
} # }}}

# shellcheck disable=SC2120
launchArchInstaller(){ # {{{
    installArchIso
    createQemuImage "$storageDir/images/arch-latest-drive.img"
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/arch-latest-drive.img" "$storageDir/isos/arch-latest.iso"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/arch-latest-drive.img" "$storageDir/isos/arch-latest.iso" "qemu-TUI"
    };}
} # }}}

launchArch(){ # {{{
    [[ ! -f "$storageDir/images/arch-latest-drive.img" ]] && {
        launchArchInstaller
        exit 0;
    }
    # shellcheck disable=SC2015
    [[ -z $1 || $1 == "gui" ]] && {
        launchQemu "$storageDir/images/arch-latest-drive.img"
    } || { [[ $1 == "qemu-TUI" ]] && {
        launchQemu "$storageDir/images/arch-latest-drive.img" "" "qemu-TUI"
    };}
} # }}}

declare -A menusAndCommands=( # {{{
    [" Arch linux installer; GUI"]="launchArchInstaller"
    [" Arch linux installer; qemu-TUI"]="launchArchInstaller qemu-TUI"

    [" Arch linux; Gui"]="launchArch"
    [" Arch linux; qemu-TUI"]="launchArch qemu-TUI"

    ["󱄅 NixOS installer; GUI"]="launchNixInstaller"
    ["󱄅 NixOS installer; qemu-TUI"]="launchNixInstaller qemu-TUI"

    ["󱄅 NixOS; GUI"]="launchNix"
    ["󱄅 NixOS; qemu-TUI"]="launchNix qemu-TUI"


    [" Alpine installer; GUI"]="launchAlpineInstaller"
    [" Alpine installer; qemu-TUI"]="launchAlpineInstaller qemu-TUI"

    [" Alpine; GUI"]="launchAlpine"
    [" Alpine; qemu-TUI"]="launchAlpine qemu-TUI"


    [" Gentoo installer; GUI"]="launchGentooInstaller"
    [" Gentoo installer; qemu-TUI"]="launchGentooInstaller qemu-TUI"

    [" Gentoo; GUI"]="launchGentoo"
    [" Gentoo; qemu-TUI"]="launchGentoo qemu-TUI"


    [" Settings"]="changeQemuSettings "
) # }}}

startQemu(){ # {{{
    chosen="$(
        echo -en "$(
            for item in "${!menusAndCommands[@]}"; do
                printf "%s \n" "$item"
            done
        )"\
        |
        pickMenu "$*"\
        |
        sed 's/.$//'
    )"
} # }}}

[[ ! -d "$storageDir/images" ]] && mkdir --parents "$storageDir/images"
[[ ! -d "$storageDir/isos" ]] && mkdir --parents "$storageDir/isos"

while true; do # {{{
    startQemu "$@"
    # shellcheck disable=SC2015
    [[ -n "$chosen" ]] && {
        [[ "$chosen" == " Settings" ]] && {
            changeQemuSettings
            continue
        } || {
            eval "${menusAndCommands["$chosen"]}"
            exit 0
        }
    } || {
        exit 0
    }
done # }}}
